import { appendFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { LanguageModelUsage, ModelMessage } from 'ai';
import { toolResultOutputToText } from '../context/tool-result-output.ts';

/**
 * Prompt cache pricing per provider (unit: $ / 1M tokens, data as of 2026-05).
 *
 * Hit discounts are not a uniform 10x; providers differ a lot:
 * - Claude: cache read = 10% of input; write 5min = 125%, 1h = 200%
 * - OpenAI: automatic caching, hit discount varies by model (4o series 50%, GPT-5 / 4.1 series 25%)
 * - Gemini: cache read = 10% of input (explicit mode also charges for storage time, not listed here)
 * - DeepSeek: cache hit = 10% of miss, no write fee, no TTL
 * - Qwen: implicit 20%, explicit 10% (same `cache_control: ephemeral` field as Anthropic)
 * - Kimi: automatic mode 25%
 * - Doubao: explicit cache, hit price = 40% of miss
 *
 * To add a model, extend this table.
 */
export interface ModelPricing {
  input: number;       // $ / 1M input tokens (cache miss)
  output: number;      // $ / 1M output tokens
  cacheWrite: number;  // $ / 1M tokens written to cache
  cacheRead: number;   // $ / 1M tokens read from cache (hit)
}

export const PRICE_TABLE: Record<string, ModelPricing> = {
  // Anthropic (latest flagship, 4.7 series released in H1 2026)
  'claude-opus-4-7':      { input: 15.00, output: 75.00, cacheWrite: 18.75, cacheRead: 1.50 },
  'claude-sonnet-4-7':    { input: 3.00,  output: 15.00, cacheWrite: 3.75,  cacheRead: 0.30 },
  'claude-haiku-4-5':     { input: 1.00,  output: 5.00,  cacheWrite: 1.25,  cacheRead: 0.10 },
  // OpenAI (GPT-5 series; GPT-5.5 defaults to 24h extended cache)
  'gpt-5-5':              { input: 5.00,  output: 20.00, cacheWrite: 5.00,  cacheRead: 0.50 },
  'gpt-5':                { input: 5.00,  output: 15.00, cacheWrite: 5.00,  cacheRead: 1.25 },
  // Google (Gemini 3 series, latest preview)
  'gemini-3-pro':         { input: 2.50,  output: 12.00, cacheWrite: 2.50,  cacheRead: 0.625 },
  'gemini-3-flash':       { input: 0.30,  output: 1.20,  cacheWrite: 0.30,  cacheRead: 0.075 },
  // Chinese providers
  'deepseek-v3-2':        { input: 0.27,  output: 1.10,  cacheWrite: 0.27,  cacheRead: 0.027 },
  'qwen3-6-plus':         { input: 0.40,  output: 1.20,  cacheWrite: 0.40,  cacheRead: 0.04 },
  'kimi-k2-6':            { input: 0.60,  output: 2.50,  cacheWrite: 0.60,  cacheRead: 0.15 },
  'doubao-2-0-pro':       { input: 0.30,  output: 0.90,  cacheWrite: 0.30,  cacheRead: 0.12 },
  // Mock model, priced like Haiku 4.5
  'mock-model':           { input: 1.00,  output: 5.00,  cacheWrite: 1.25,  cacheRead: 0.10 },
};

export interface StepUsage {
  /** Uncached input tokens, billed at the normal input price. */
  inputTokens: number;
  /** Output tokens generated by the model. */
  outputTokens: number;
  /** Input tokens that hit an existing prompt cache. */
  cacheReadTokens: number;
  /** Input tokens written to the prompt cache by this request. */
  cacheWriteTokens: number;
}

export interface StepRecord extends StepUsage {
  kind?: 'main' | 'summary';
  usage?: LanguageModelUsage;
  durationMs?: number;
  /** Unix timestamp when this model request finished. */
  ts: number;
  /** Model id used for this request. */
  model: string;
  /** Cost of this request in USD; undefined when the model has no known price. */
  cost?: number;
}

export interface UsageTotals {
  /** Total uncached input tokens. */
  inputTokens: number;
  /** Total output tokens. */
  outputTokens: number;
  /** Total cache read tokens. */
  cacheReadTokens: number;
  /** Total cache write tokens. */
  cacheWriteTokens: number;
  /** Total actual cost of the priced requests; undefined when no request had a known price. */
  cost?: number;
  /** cache read / all input-like tokens. */
  hitRate: number;
  /** Cost if every input-like token had missed the cache; undefined like `cost`. */
  baselineCost?: number;
  /** Cost saved compared with no cache; undefined like `cost`. */
  savedCost?: number;
  /** Number of recorded model requests. */
  steps: number;
}

export interface TokenStatus {
  /** Estimated tokens in the current context. */
  tokens: number;
  /** Current context as a percentage of the fixed window. */
  percent: number;
  /** Whether the threshold for context defense actions is reached. */
  needsAction: boolean;
}

/** Model context window size; the shared threshold base for status and defense. */
export const CONTEXT_WINDOW = 200_000;

/**
 * Tracks token state at two different scopes:
 *
 * 1. Current context estimate: used by defense / compaction;
 * 2. Usage and cost of each model request: used by /usage.
 *
 * One object manages both, but they never share a number.
 */
export class TokenTracker {
  /** Usage details of each successful model request, accumulated across agentLoops. */
  private steps: StepRecord[] = [];
  /** Optional JSONL usage log path. */
  private logPath?: string;
  /** Full prompt token count from the last API response. */
  private lastPreciseCount = 0;
  /** Message chars added since the last API calibration, not yet reflected in the API count. */
  private pendingChars = 0;
  /** Price from the current model config (cost in models.json); overrides the built-in table and updates on model switch. */
  private pricing?: ModelPricing;
  /** Sum of each step's hypothetical no-cache cost, at the price in effect at request time (old requests are not repriced after a model switch). */
  private baselineCost = 0;
  /** Whether any recorded request had a known price. */
  private priced = false;
  /** Current model's context window, used for the status percentage. */
  contextWindow = CONTEXT_WINDOW;

  constructor(logPath?: string) {
    this.logPath = logPath;
    if (logPath) mkdirSync(dirname(logPath), { recursive: true });
  }

  /** Calibrates the current context baseline with the full prompt token count from the API. */
  updateFromAPI(promptTokens: number): void {
    this.lastPreciseCount = promptTokens;
    this.pendingChars = 0;
  }

  /** Builds the initial context estimate from the loaded message history. */
  setEstimatedTokens(tokens: number): void {
    this.lastPreciseCount = Math.max(0, tokens);
    this.pendingChars = 0;
  }

  /** Adds a new message's estimated chars to the current context. */
  addMessage(message: ModelMessage): void {
    this.pendingChars += countMessageChars(message);
  }

  /** Adds several new messages' estimated chars to the current context. */
  addMessages(messages: ModelMessage[]): void {
    for (const message of messages) {
      this.addMessage(message);
    }
  }

  /** Adjusts the context estimate by the char difference before and after replacing messages. */
  replaceMessages(before: ModelMessage[], after: ModelMessage[]): void {
    this.pendingChars += countMessagesChars(after) - countMessagesChars(before);
  }

  /** Current context token estimate: last API baseline plus local message delta. */
  get estimatedTokens(): number {
    return Math.max(0, this.lastPreciseCount + Math.ceil(this.pendingChars / 4));
  }

  /** Current model's price (overrides the built-in table); undefined uses the built-in table, and a model in neither has no cost. Only affects later requests. */
  setPricing(pricing: ModelPricing | undefined): void {
    this.pricing = pricing;
  }

  /** Current context status relative to the model window (default 200k). */
  get status(): TokenStatus {
    const tokens = this.estimatedTokens;
    const percent = Math.round((tokens / this.contextWindow) * 100);
    return {
      tokens,
      percent,
      needsAction: percent >= 75,
    };
  }

  /**
   * Records one model request.
   */
  record(model: string, usage: StepUsage, details: Pick<StepRecord, 'kind' | 'usage' | 'durationMs'> = { kind: 'main' }): StepRecord {
    const price = this.pricing ?? PRICE_TABLE[model];
    let cost: number | undefined;
    if (price) {
      cost = computeCost(usage, price);
      const inputLike = usage.inputTokens + usage.cacheReadTokens + usage.cacheWriteTokens;
      this.baselineCost += (inputLike * price.input + usage.outputTokens * price.output) / 1_000_000;
      this.priced = true;
    }
    const record: StepRecord = { ts: Date.now(), model, ...(cost === undefined ? {} : { cost }), ...usage, ...details };
    this.steps.push(record);

    if (this.logPath) {
      appendFileSync(this.logPath, JSON.stringify(record) + '\n');
    }
    return record;
  }

  /** Returns total usage, cache and cost over this tracker's lifetime. */
  totals(): UsageTotals {
    const t = this.steps.reduce(
      (a, s) => ({
        inputTokens: a.inputTokens + s.inputTokens,
        outputTokens: a.outputTokens + s.outputTokens,
        cacheReadTokens: a.cacheReadTokens + s.cacheReadTokens,
        cacheWriteTokens: a.cacheWriteTokens + s.cacheWriteTokens,
        cost: a.cost + (s.cost ?? 0),
      }),
      { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, cost: 0 },
    );
    const totalInputLike = t.inputTokens + t.cacheReadTokens + t.cacheWriteTokens;
    const hitRate = totalInputLike > 0 ? t.cacheReadTokens / totalInputLike : 0;
    // Hypothetical no-cache cost: pay full price for every input-like token as a miss
    const { cost, ...tokens } = t;
    if (!this.priced) return { ...tokens, hitRate, steps: this.steps.length };
    const baselineCost = this.baselineCost;
    return { ...tokens, cost, hitRate, baselineCost, savedCost: baselineCost - cost, steps: this.steps.length };
  }

  /** Returns recent model request records without changing totals. */
  recent(n: number): StepRecord[] {
    return this.steps.slice(-n);
  }
}

function countMessageChars(message: ModelMessage): number {
  let chars = 0;
  if (typeof message.content === 'string') {
    return message.content.length;
  }
  if (!Array.isArray(message.content)) return chars;

  for (const part of message.content) {
    if ('text' in part && typeof part.text === 'string') {
      chars += part.text.length;
    } else if ('output' in part) {
      chars += part.output.type === 'json'
        ? JSON.stringify(part.output.value).length
        : toolResultOutputToText(part.output).length;
    } else if ('input' in part) {
      chars += JSON.stringify(part.input)?.length ?? 0;
    }
  }
  return chars;
}

function countMessagesChars(messages: ModelMessage[]): number {
  let chars = 0;
  for (const message of messages) {
    chars += countMessageChars(message);
  }
  return chars;
}

/** Estimates history tokens from message chars, for context defense. */
export function estimateMessageTokens(messages: ModelMessage[]): number {
  const chars = countMessagesChars(messages);
  // 4 chars per token, with 1.2x safety factor for Chinese
  return Math.ceil((chars / 4) * 1.2);
}

export function computeCost(usage: StepUsage, p: ModelPricing): number {
  return (
    (usage.inputTokens * p.input
      + usage.outputTokens * p.output
      + usage.cacheReadTokens * p.cacheRead
      + usage.cacheWriteTokens * p.cacheWrite)
    / 1_000_000
  );
}

/**
 * Normalizes the AI SDK usage object into four token kinds.
 *
 * The AI SDK splits input tokens in `inputTokenDetails` into uncached, cache read and cache write.
 * Its `inputTokens` is the total of all three; this keeps the tracker's four-kind billing scheme,
 * so `StepUsage.inputTokens` means uncached input tokens.
 */
export function normalizeUsage(usage: LanguageModelUsage | undefined): StepUsage {
  if (!usage) return { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 };

  const cacheReadTokens = usage.inputTokenDetails.cacheReadTokens ?? 0;
  const cacheWriteTokens = usage.inputTokenDetails.cacheWriteTokens ?? 0;
  const inputTokens =
    usage.inputTokenDetails.noCacheTokens
    ?? Math.max(
      0,
      (usage.inputTokens ?? 0) - cacheReadTokens - cacheWriteTokens,
    );

  return {
    inputTokens: Math.max(0, inputTokens),
    outputTokens: usage.outputTokens ?? 0,
    cacheReadTokens,
    cacheWriteTokens,
  };
}
